"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"

add_newline = false

[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true
